-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 22:01:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provinces` (
  `ProvinceID` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ProvinceID`));


-- -----------------------------------------------------
-- Table `mydb`.`Localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localities` (
  `LocalityID` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `ProvinceID` INT NOT NULL,
  PRIMARY KEY (`LocalityID`),
  INDEX (`ProvinceID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`ProvinceID`)
    REFERENCES `mydb`.`Provinces` (`ProvinceID`));


-- -----------------------------------------------------
-- Table `mydb`.`Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stores` (
  `StoreID` INT NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `PostalCode` VARCHAR(10) NOT NULL,
  `LocalityID` INT NOT NULL,
  `ProvinceID` INT NOT NULL,
  PRIMARY KEY (`StoreID`),
  INDEX (`LocalityID` ASC) VISIBLE,
  INDEX (`ProvinceID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`LocalityID`)
    REFERENCES `mydb`.`Localities` (`LocalityID`),
  CONSTRAINT ``
    FOREIGN KEY (`ProvinceID`)
    REFERENCES `mydb`.`Provinces` (`ProvinceID`));


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `ClientID` INT NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `PostalCode` VARCHAR(10) NOT NULL,
  `LocalityID` INT NOT NULL,
  `ProvinceID` INT NOT NULL,
  `PhoneNumber` INT NOT NULL,
  PRIMARY KEY (`ClientID`),
  INDEX (`LocalityID` ASC) VISIBLE,
  INDEX (`ProvinceID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`LocalityID`)
    REFERENCES `mydb`.`Localities` (`LocalityID`),
  CONSTRAINT ``
    FOREIGN KEY (`ProvinceID`)
    REFERENCES `mydb`.`Provinces` (`ProvinceID`));


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `OrderID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `DateTime` DATETIME NOT NULL,
  `DeliveryType` VARCHAR(20) NOT NULL,
  `TotalPrice` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX (`ClientID` ASC) VISIBLE,
  INDEX (`StoreID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Clients` (`ClientID`),
  CONSTRAINT ``
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Stores` (`StoreID`));


-- -----------------------------------------------------
-- Table `mydb`.`OrderProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderProducts` (
  `OrderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `ProductID`),
  CONSTRAINT ``
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Orders` (`OrderID`));


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductID` INT NOT NULL,
  `name` ENUM('pizza', 'drink', 'hamburguer') NOT NULL,
  PRIMARY KEY (`ProductID`),
  CONSTRAINT `fk_Products_OrderProducts1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`OrderProducts` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`PizzaCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PizzaCategories` (
  `name` VARCHAR(45) NOT NULL,
  `idP` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drinks` (
  `idDrink` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `Image` JSON NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idDrink`),
  CONSTRAINT `fk_Drinks_Categories1`
    FOREIGN KEY (`idDrink`)
    REFERENCES `mydb`.`Products` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`StoresEmployees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StoresEmployees` (
  `EmployeeID` INT NULL DEFAULT NULL,
  `StoreID` INT NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  `PhoneNumber` INT NOT NULL,
  `JobType` ENUM('cook', 'worker', 'delivery') NOT NULL,
  PRIMARY KEY (`EmployeeID`),
  PRIMARY KEY (`EmployeeID`, `StoreID`),
  INDEX (`StoreID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Stores` (`StoreID`));


-- -----------------------------------------------------
-- Table `mydb`.`Deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deliveries` (
  `DeliveryID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `DeliveryDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`DeliveryID`),
  PRIMARY KEY (`DeliveryID`, `OrderID`),
  INDEX (`OrderID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Orders` (`OrderID`));


-- -----------------------------------------------------
-- Table `mydb`.`Cooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooks` (
  `CookID` INT NOT NULL,
  `Specialization` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CookID`),
  CONSTRAINT `fk_Cooks_StoresEmployees1`
    FOREIGN KEY (`CookID`)
    REFERENCES `mydb`.`StoresEmployees` (`JobType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryBoy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryBoy` (
  `idDeliveryEmployes` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Deliveries_DeliveryID` INT NOT NULL,
  `Deliveries_OrderID` INT NOT NULL,
  PRIMARY KEY (`idDeliveryEmployes`),
  INDEX `fk_DeliveryBoy_Deliveries1_idx` (`Deliveries_DeliveryID` ASC, `Deliveries_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_DeliveryBoy_StoresEmployees1`
    FOREIGN KEY (`idDeliveryEmployes`)
    REFERENCES `mydb`.`StoresEmployees` (`JobType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DeliveryBoy_Deliveries1`
    FOREIGN KEY (`Deliveries_DeliveryID` , `Deliveries_OrderID`)
    REFERENCES `mydb`.`Deliveries` (`DeliveryID` , `OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hamburguers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hamburguers` (
  `idHamburguer` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `Image` JSON NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idHamburguer`),
  CONSTRAINT `fk_Hamburguers_Categories1`
    FOREIGN KEY (`idHamburguer`)
    REFERENCES `mydb`.`Products` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizzas` (
  `IdPizza` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `Image` JSON NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `categoriesID` INT NOT NULL,
  PRIMARY KEY (`IdPizza`),
  CONSTRAINT `fk_Pizzas_PizzaCategories1`
    FOREIGN KEY (`IdPizza`)
    REFERENCES `mydb`.`PizzaCategories` (`idP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizzas_Categories1`
    FOREIGN KEY (`IdPizza`)
    REFERENCES `mydb`.`Products` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
